---
- homebrew: name={{ item }} state=latest
  with_items:
    - rbenv
    - ruby-build

- template: src=rbenv.zsh.j2 dest={{ zsh_custom_dir }}/rbenv.zsh

- homebrew: name={{ item }} state=latest
  with_items:
    - readline
    - openssl

- shell: >
    eval "$(rbenv init -)";
    rbenv install {{ rbenv_ruby_version }}
    creates=~/.rbenv/versions/{{ rbenv_ruby_version }}


- shell: >
    eval "$(rbenv init -)";
    rbenv global
  register: rbenv_global_version
  changed_when: false

- shell: >
    eval "$(rbenv init -)";
    rbenv global {{ rbenv_ruby_version }}
  when: rbenv_global_version.stdout != rbenv_ruby_version

# NOTE: we cannot use ansible gem module which install gems to /usr/local/lib/ruby/gems
#- gem: name={{ item }} state=latest user_install=yes executable=~/.rbenv/shims/gem
#  notify: rbenv rehash
#  with_items: rbenv_global_gems

- shell: >
    ~/.rbenv/versions/{{ rbenv_ruby_version }}/bin/gem install {{ item }}
  notify: rbenv rehash
  with_items: rbenv_global_gems
